spring:
  application:
    name: notification-service
  cloud:
    stream:
      bindings:
        consumeNotification-in-0:
          destination: notification-topic
      kafka:
        binder:
          brokers: localhost:9092
server:
  port: 0
